// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wackfusxeswwawbblrsf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndhY2tmdXN4ZXN3d2F3YmJscnNmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwNDY0MDcsImV4cCI6MjA3MDYyMjQwN30.-letwdK5IcFnIFNRMq4Vh_lYFl_Wfh8V9qjgJo0yQuY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});